Employee Management/Models/AssignTask.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Employee_Management.Models
{
    public class AssignTask
    {
        public int AssignTaskId { get; set; }
        public string AssignTaskName { get; set; }
        public string AssignTaskDec { get; set; }
        public int AssignTaskEmployeeId { get; set; }
        public string Priority { get; set; }
        public string AssignTaskStatus { get; set; }
        [NotMapped]
        public string EmpName { get; set; }

    }
}

Employee Management/Controllers/AssignTaskController.cs
using Employee_Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;

namespace Employee_Management.Controllers
{

    [AllowAnonymous]
    public class AssignTaskController : Controller
    {
        private readonly IAssignTaskRepository assignTaskRepository;        
        private readonly IEmployeeRepository employeeRepository;

        public AssignTaskController(IAssignTaskRepository _assignTaskRepository, IEmployeeRepository employeeRepository)
        {
            assignTaskRepository = _assignTaskRepository;
            this.employeeRepository = employeeRepository;
        }

        public IActionResult Index()
        {
            var pay = assignTaskRepository.GetAllAssignTask().ToList();
            var emp = employeeRepository.GetAllEmployee().ToList();
            foreach (var item in pay)
            {
                item.EmpName = emp.FirstOrDefault(x => x.ID == item.AssignTaskEmployeeId).Name;

            }
            var model = assignTaskRepository.GetAllAssignTask();

            return View(model);
        }

        public IActionResult EmpIndex()
        {
            Employee emp = new Employee();
            var idstring = HttpContext.Session.GetString("ID");
            var id = Int32.Parse(idstring);
            var model = assignTaskRepository.GetAllAssignTask().Where(emp => emp.AssignTaskEmployeeId == id);
            //ViewBag.Employee = employeeRepository.GetAllEmployee().ToString();

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var emps = employeeRepository.GetAllEmployee();
            ViewBag.Employee = emps.Select(x => new SelectListItem() { Text = x.Name.ToString(), Value = x.ID.ToString() });

            AssignTask po = new AssignTask();
            return PartialView("Create", po);
            //return View();
        }

        [HttpPost]
        public IActionResult Create(AssignTask assignTask)
        {
            if (ModelState.IsValid)
            {
                assignTaskRepository.Add(assignTask);
                //return PartialView("Create", position);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var emps = employeeRepository.GetAllEmployee();
            ViewBag.Employee = emps.Select(x => new SelectListItem() { Text = x.Name.ToString(), Value = x.ID.ToString() });
            var assignTask = assignTaskRepository.GetAssignTask(id);
            return PartialView("Edit", assignTask);
        }

        [HttpPost]
        public IActionResult Edit(AssignTask po)
        {
            assignTaskRepository.Update(po);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            assignTaskRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Employee Management/Views/AssignTask/Create.cshtml
@model AssignTask
@{
   
    ViewData["Title"] = "Edit AssingTask";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Create</h1>

<h4>Task</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          @*  <input hidden asp-for="AssignTaskId" />*@
      
            <div class="form-group">
                <label asp-for="AssignTaskName" class="control-label"></label>
                <input asp-for="AssignTaskName" class="form-control" />
                <span asp-validation-for="AssignTaskName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssignTaskDec" class="control-label"></label>
                <input asp-for="AssignTaskDec" class="form-control" />
                <span asp-validation-for="AssignTaskDec" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="AssignTaskEmployeeId" class="control-label">Employee</label>
                <select asp-for="AssignTaskEmployeeId" asp-items="@ViewBag.Employee" class="form-control">
                    <option value="">Please Select</option>
                </select>
                <span asp-validation-for="AssignTaskEmployeeId" class="text-danger"></span>
            </div>
            
             <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
               
                <select class="form-control" asp-for="Priority" >
                    <option value="High">High</option>
                    <option value="Medium">Medium</option>
                     <option value="Low">Low</option>
                </select>
            </div>
             <div class="form-group">
                <label asp-for="AssignTaskStatus" class="control-label"></label>
               
                <select class="form-control" asp-for="AssignTaskStatus" >
                   <option value="On Hold">On Hold</option>
                    <option value="Completed">Completed</option>
                    <option value="In Progress">In Progress</option>
                      <option value="In To Do List">In To Do List</option>
                </select>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/js/customScript.js"></script>
   
}

Employee Management/Views/AssignTask/Edit.cshtml
@model AssignTask
@{
   
    ViewData["Title"] = "Edit AssingTask";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Edit</h1>

<h4>Task</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input hidden asp-for="AssignTaskId" />
      
            <div class="form-group">
                <label asp-for="AssignTaskName" class="control-label"></label>
                <input asp-for="AssignTaskName" class="form-control" />
                <span asp-validation-for="AssignTaskName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssignTaskDec" class="control-label"></label>
                <input asp-for="AssignTaskDec" class="form-control" />
                <span asp-validation-for="AssignTaskDec" class="text-danger"></span>
            </div>
               <div class="form-group">
                <label asp-for="AssignTaskEmployeeId" class="control-label">Employee</label>
                <select asp-for="AssignTaskEmployeeId" asp-items="@ViewBag.Employee" class="form-control">
                    <option value="">Please Select</option>
                </select>
                <span asp-validation-for="AssignTaskEmployeeId" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
               
                <select class="form-control" asp-for="Priority" >
                    <option value="High">High</option>
                    <option value="Medium">Medium</option>
                     <option value="Low">Low</option>
                </select>
            </div>
              <div class="form-group">
                <label asp-for="AssignTaskStatus" class="control-label"></label>
               
                <select class="form-control" asp-for="AssignTaskStatus" >
                    <option value="On Hold">On Hold</option>
                    <option value="Completed">Completed</option>
                    <option value="In Progress">In Progress</option>
                     <option value="In To Do List">In To Do List</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/js/customScript.js"></script>
   
}

Employee Management/Views/AssignTask/EmpIndex.cshtml
@model IEnumerable<AssignTask>

@{
    ViewBag.Title = "AssignTask List";
}
<h1 class="text-center">Assign Task List</h1>
<hr />

@*<a asp-controller="AssignTask" asp-action="Create" style="width:auto" class="btn btn-primary m-1">Create Task</a>*@

<table class="table mt-2">
    <thead class="thead-light">
        <tr>
            
            <th>Task Name</th>
            <th>Decription</th>
            <th>Priority</th>
           @*<th>Employee</th>*@
           @* <th>Action</th>*@
        </tr>
    </thead>
    <tbody>
        @foreach(var assignTask in Model)
        {
            <tr>
               
                <td>@assignTask.AssignTaskName</td>
                <td>@assignTask.AssignTaskDec</td>
                <td>@assignTask.Priority</td>
               @*<td>@assignTask.EmpName</td>*@
              @*  <td>
                    <div>

                         <a asp-action="Edit" asp-route-id="@assignTask.AssignTaskId"> <i class="nav-icon fas fa-pen"></i></a> |
                          <a asp-action="Delete" asp-route-id="@assignTask.AssignTaskId"> <i class="nav-icon fas fa-trash"></i></a>
                    </div>
                    
                </td>*@
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script src="~/js/customScript.js"></script>
}

Employee Management/Views/AssignTask/Index.cshtml
@model IEnumerable<AssignTask>

@{
    ViewBag.Title = "AssignTask List";
}
<h1 class="text-center">Assign Task List</h1>
<hr />

<a asp-controller="AssignTask" asp-action="Create" style="width:auto" class="btn btn-primary m-1">Create Task</a>

<table class="table mt-2">
    <thead class="thead-light">
        <tr>
            
            <th>Task Name</th>
            <th>Decription</th>
            <th>Priority</th>
            <th>Status</th>
           <th>Employee</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var assignTask in Model)
        {
            <tr>
               
                <td>@assignTask.AssignTaskName</td>
                <td>@assignTask.AssignTaskDec</td>
                <td>@assignTask.Priority</td>
                <td>@assignTask.AssignTaskStatus</td>
               <td>@assignTask.EmpName</td>
                <td>
                    <div>

                         <a asp-action="Edit" asp-route-id="@assignTask.AssignTaskId"> <i class="nav-icon fas fa-pen"></i></a> |
                          <a asp-action="Delete" asp-route-id="@assignTask.AssignTaskId"> <i class="nav-icon fas fa-trash"></i></a>
                    </div>
                    
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script src="~/js/customScript.js"></script>
}