Employee Management/Controllers/PayController.cs
using Employee_Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace Employee_Management.Controllers
{
    [AllowAnonymous]
    public class PayController : Controller
    {
        private readonly IPayRepository payRepository;        
        private readonly IEmployeeRepository employeeRepository;

        public PayController(IPayRepository _payRepository, IEmployeeRepository employeeRepository)
        {
            payRepository = _payRepository;
            this.employeeRepository = employeeRepository;
        }

        public IActionResult Index()
        {
            var pay = payRepository.GetAllPay().ToList();
            var emp = employeeRepository.GetAllEmployee().ToList();
            foreach (var item in pay)
            {
                item.EmpName = emp.FirstOrDefault(x => x.ID == item.PayEmployeeId).Name;    
          
            }
           
            var model = payRepository.GetAllPay();
            
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var emps = employeeRepository.GetAllEmployee();
            ViewBag.Employee = emps.Select(x => new SelectListItem() { Text = x.Name.ToString(), Value = x.ID.ToString() });

            Pay po = new Pay();
            return PartialView("Create", po);
            //return View();
        }

        [HttpPost]
        public async Task<ActionResult> PostToPaypall(Pay pay)
        {
            if (ModelState.IsValid)
            {
              //  using var client = new HttpClient();

                string url = "https://www.sandbox.paypal.com/cgi-bing/webscr?cmd=_xclick&amount=" + pay.Amount
                    + "&business=sb-kpmax15511933@personal.example.com&item_name=Paycheck_From_EMS&return=https://localhost:44324/Pay/Create";

                Response.Redirect(url);

              //  var result = await client.GetAsync(url);

              //  payRepository.Add(pay);
                //return PartialView("Create", position);
              //  return RedirectToAction("Index");
            }
            return View();
        }


        [HttpPost]
        public IActionResult Create(Pay pay)
        {
            if (ModelState.IsValid)
            {
                payRepository.Add(pay);
                //return PartialView("Create", position);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var emps = employeeRepository.GetAllEmployee();
            ViewBag.Employee = emps.Select(x => new SelectListItem() { Text = x.Name.ToString(), Value = x.ID.ToString() });
            var pay = payRepository.GetPay(id);
            return PartialView("Edit", pay);
        }

        [HttpPost]
        public IActionResult Edit(Pay po)
        {
            payRepository.Update(po);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            payRepository.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult CheckOut()
        {
            return View();
        }
    }
}

Employee Management/Views/Shared/NotFound.cshtml
@{ 
    ViewBag.Title = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="Index" asp-controller="Home">
    Click here to navigate the Home page
</a>

Employee Management/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager;
 @using Microsoft.AspNetCore.Http;

@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
   
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> EMS | Dashboard </title>
    <link rel="icon" type="image/x-icon" href="~/Frontend/dist/img/Logo.png">
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/Frontend/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Frontend/dist/css/adminlte.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>

<body class="hold-transition sidebar-mini"> @*sidebar-collapse*@


    <div class="wrapper">

      
            <!-- Navbar -->
            <nav class="main-header navbar navbar-expand navbar-white navbar-light">
                <!-- Left navbar links -->
            @if (signInManager.IsSignedIn(User) || @HttpContextAccessor.HttpContext.Session.GetString("ID") != null){
            <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                    </li> 
                </ul>
                }
                <!-- Right navbar links -->
           <ul class="navbar-nav ml-auto">
                    <!-- Navbar Search -->
                    @* <li class="nav-item d-none d-sm-inline-block"> 
                        @Html.ActionLink("Home", "Index", "Home", new { @class = "a.nav-link" }, null)
                        </li>*@
                    @* <li class="nav-item d-none d-sm-inline-block">
                        <a href="#" class="nav-link">Profile</a>
                        </li>*@
                    @if (signInManager.IsSignedIn(User))
                    {
                        <li class="nav-item d-none d-sm-inline-block">
                            <form method="post" asp-action="Logout" asp-controller="Account">
                                <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                    Logout @User.Identity.Name
                                </button>
                            </form>
                        </li>
                    }
                    else if( @HttpContextAccessor.HttpContext.Session.GetString("ID") != null )
                    {
                       <li class="nav-item d-none d-sm-inline-block">
                            <form method="post" asp-action="Logout" asp-controller="Dashboard">
                                <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                    Logout @HttpContextAccessor.HttpContext.Session.GetString("Name")
                                </button>
                            </form>
                        </li>
                    }
                    else{
                         <li class="nav-item d-none d-sm-inline-block">
                               <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                    Hello!
                                </button>
                        </li>
                    }
                </ul>
        </nav>
        
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="~/Frontend/dist/img/Logo.png" alt="EMS Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">EMS Soft</span>
            </a>
           
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
               @* <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/Frontend/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div> 
                    <div class="info">
                        <a href="#" class="d-block">Abhishek Gupta</a>
                    </div>
                </div>*@

                <!-- SidebarSearch Form -->
              
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                             with font-awesome or any other icon font library -->
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                           <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Dashboard")"><i class="nav-icon fas fa-home"></i><span class="m-3"> Home</span> </a>
                            </li>
                           
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Home")"><i class="nav-icon fas fa-users"></i><span class="m-3"> Employees</span> </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Department")"><i class="nav-icon fas fa-building"></i><span class="m-3"> Departments</span> </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Position")"><i class="nav-icon fas fa-sitemap"></i><span class="m-3"> Positions</span> </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Schedule")"><i class="nav-icon fas fa-tasks"></i><span class="m-3"> Schedule</span> </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "AssignTask")"><i class="nav-icon fas fa-calendar"></i><span class="m-3"> Tasks</span> </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Leave")"><i class="nav-icon fas fa-circle"></i><span class="m-3"> Leave Requests</span> </a>
                                </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Pay")"><i class="nav-icon fas fa-credit-card"></i><span class="m-3"> Pay</span> </a>
                                </li>
                          <li class="nav-item">
                               <a class="nav-link" href="@Url.Action("Index", "Hour")"><i class="nav-icon fas fa-user-clock"></i><span class="m-3"> Hours Worked</span> </a>
                             </li>  
                        }
                        @if(@HttpContextAccessor.HttpContext.Session.GetString("ID") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Dashboard")"><i class="nav-icon fas fa-home"></i><span class="m-3"> Home</span> </a>
                            </li>
                             <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("EmpIndex", "AssignTask")"><i class="nav-icon fas fa-calendar"></i><span class="m-3"> Tasks</span> </a>
                            </li>
                             <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("EmpIndex", "Leave")"><i class="nav-icon fas fa-circle"></i><span class="m-3"> Leave Requests</span> </a>
                             </li>  
                            <li class="nav-item">
                               <a class="nav-link" href="@Url.Action("EmpIndex", "Hour")"><i class="nav-icon fas fa-user-clock"></i><span class="m-3"> Hours Worked</span> </a>
                             </li>  
                        }    
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
           
            <!-- /.sidebar -->
        </aside>
        
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
       
            <!-- Main content -->
            <div class="content">
                <div class="container-fluid ">
                         @RenderBody()
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2022 Made by 3techatiers with LOVE</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 1.0
            </div>
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    @await RenderSectionAsync("Scripts", required: false)
    <!-- jQuery -->
    <script src="~/Frontend/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Frontend/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/Frontend/dist/js/adminlte.js"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="~/Frontend/plugins/chart.js/Chart.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Frontend/dist/js/pages/dashboard3.js"></script>
    
</body>
</html>